### ISSUE TITLE
some feedback

### ISSUE THREAD

**Issue by timomayer** [virtualidentityag/conditional-resource-loader#2]
@smohadjer 
in line 30 we should check if path starts with http rather then existance cause of something like /path/http/willfail. same for 38 path should end with .css
line 57 pls collect all <link> tags in a string and place them into <head> together thats way more performant then puttin each single file into <head>
are you sure script execution gets blocked until the css files are loaded? i am not sure about that and if thats not the case line 67 may sent a false resourcesReady

**Comment by smohadjer** [comment]
@timomayer 
- Rather than checking if path starts with http I check for existence of http:// and https:// strings, because we may still have a relative path with http as top folder.
- I used an array rather than a string to avoid multiple DOM insertions.
- I had not assumed that script execution gets blocked, my thinking was that we don't need to wait for conditional styles to load if we have no conditional scripts. But I was wrong and this is not safe. Now resourcesReady fires only if there are no styles AND no scripts to load or it fires only after all styles and scripts are loaded. This is safer since we don't want any plugin to initialize, regardless of whether it was a conditional resource or not, as long as all styles are not loaded.
